# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('phone_type', models.CharField(max_length=50)),
                ('street1', models.CharField(blank=True, max_length=150)),
                ('street2', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_zip', models.CharField(blank=True, max_length=5)),
                ('second_number', models.CharField(blank=True, max_length=50)),
                ('second_type', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('insurance', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
